apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: restapinode
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: restapinode
    spec:
      containers:
      - name: restapinode
        image: docker.io/anujaharane/test:4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# vim: set ts=2 expandtab!: