apiVersion: v1
kind: Service
metadata:
  name: restnodeapp
  labels:
    app: restnodeapp
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP    
  selector:
    app: restnodeapp
  type: LoadBalancer