apiVersion: v1
kind: Service
metadata:
  name: restapinode
  labels:
    app: restapinode
spec:
  ports:
  - port: 3000
    nodePort: 30062
    protocol: TCP    
  selector:
    app: restapinode
  type: LoadBalancer