apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP    
  selector:
    app: nodeapp
  type: LoadBalancer